sudo: required
dist: xenial

branches:
  only:
    - master

before_install: 
  - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-full

install: true

script:
  - mkdir _build
  - make
  - mv ./*.pdf _build/
  - make clean
  - chmod +x build.sh
  - ./build.sh